### ISSUE TITLE
[docs] 新文章：嘀咕（哔哔）部署指南

### ISSUE THREAD

**Issue by eallion** [eallion/hugo#32]
https://eallion.com/talks/

**Comment by blue-isle** [comment]
从哪能看到详细教程，我对嘀咕真是低估了，哈哈哈，谢谢

**Comment by eallion** [comment]
开坑未写。

**Comment by luolovehk** [comment]
一人血书求更新嘀咕部署~~

**Comment by eallion** [comment]
@luolovehk @blue-isle 

https://eallion.com/memos-deployment/
